Add BDD and unit tests, realized interface ICandidatesRepository
5yxar/Bruhunter pull request #10
Opened 2021-11-18 20:02 UTC by 5yxar

### ✨ Изменения какого характера входят в данный PR? (Фикс бага, фича)
Добавлены интеграционные (с использованием BDD подхода) и юнит тесты
Добавлен интерфейс ICandidatesRepository
Изменена реализация RepositoryBase.
### ⤵️ Текущее поведение системы
Тесты не проводятся
В сервисах прокидывается класс CandidatesRepository напрямую
В RepositoryBase нельзя переопределить ничего кроме connectionString
### 🆕 Новое поведение системы
Добавлены юнит и интеграционные (с использованием BDD подхода) тесты
Можно реализовывать интерфейс ICandidatesRepository по своему
В RepositoryBase передается не connectionString а экземпляр класса LiteDb 
### 🐛 Рекомендации для тестирования
-
### 📝 Ссылки на связанные задачи
https://github.com/5yxar/Bruhunter/issues/8
### Чеклист (заполняется ревьюером)
- [ ] Соблюдается сервисная архитектура
- [ ] Не добавляются лишние ссылки между проектами
- [ ] Сборка проходит
- [ ] Тесты проходят

2021-11-19 06:22 UTC, picolino requested changes
Еще отсутствует некоторое понимание базовых концепций, но это придет с практикой написания тестов.

Еще кое-что. Сейчас проект с тестами превращается в мусорку, Давай строить иерархию:

```
Bruhunter.Tests
    - Common // Сюда перетащи все, что останется
    - IntegrationTests
        + FeatureFixtureBase.cs
        - Features // Сюда перетащи все интеграционные тесты и определения.
    - UnitTests
        + TestBase.cs // Сделай базовый класс для всех Unit-тестов. Туда можно вынести моки и тестируемые сервисы. Почти по аналогии с FeatureFixtureBase
        - CandidatesServiceTests // В эту папку положи существующие тесты (When)
```

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/AddCandidate_feature.cs
> +                                _ => Then_database_should_contain_candidate())
Давай чуть поровнее сделаем этот тест, некорректные отступы очень раздражают при чтении кода.
Тут будет лучше сделать так:

```cs
            await Runner.AddAsyncSteps(
                    _ => Given_candidate(GiveMe.Candidate()
                                               .WithId(Guid.Empty)
                                               .WithFirstName("Первое")
                                               .WithSecondName("Второе")
                                               .Please()),
                    _ => When_add_candidate(),
                    _ => Then_database_should_contain_candidate())
                .RunAsync();
```

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/AddCandidate_feature_definitions.cs
> +        private CandidateDocument candidateBeforeInsert;
Я помню, что я назвал таким образом переменную, но это не лучшее название для нее в тесте.
Лучше находится в контексте теста и обозвать ее `candidateBeforeAddition`. Так как мы не "вставляем" кандидата, а "добавляем".

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/AddCandidate_feature_definitions.cs
> +            Assert.Single(candidates);
Наименование определения для теста должно **полностью** соответствовать его содержимому.

В содержимом этого теста ты проверяешь, что в репозитории находится **только один кандидат**.

Можно намного улучшить этот тест, если дать изначальному кандидату какой-либо реальный идентификатор:

```cs
var candidateId = Guid.NewGuid();

... GiveMe.Candidate().WithId(candidateId) ...
```

А затем проверить наличие в базе **именно этого идентификатора**:

```cs
_ => Then_database_should_contain_candidate_with_id(candidateId)
```

И в теле определения (Then) сделать минимально достаточную проверку на это условие. Что у тебя в базе данных находится **не только один, а хотя-бы один** кандидат с нужным идентификатором.

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +    public partial class DeleteCandidate_feature:FeatureFixtureBase
Ну чё они слиплись?))

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +                               .RunAsync();
Такая же штука с отступами и данными кандидата

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +        public async Task Then_database_should_not_contain_candidate()
Название теста не совсем отображает его суть. Можно сделать по аналогии с тестами на добавление кандидата. Добавив айдишник и т.д. Так ты сделаешь тест более конкретным

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +        }
А для чего ты так сделал? У тебя из `GetAllCandidates` возвращается универсальный `IEnumerable`. Зачем его дополнительно к листу приводить? Лишний код. Причем много кода. И некрасивого, с кастом, айайай

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/GetCandidates_feature.cs
> +        }
Вот тут более-менее нормальные отступы, хотя много пространства слева, но нарушается последовательность AAA (Arrange, Act, Assert) или в нашем случае GWT (Given, When, Then). Каждый тест должен содержать сначала G потом W и только затем T:

```cs
            await Runner.AddAsyncSteps(
                    _ => Given_candidate(GiveMe.Candidate()
                                               .WithId(Guid.Empty)
                                               .WithFirstName("Первое")
                                               .WithSecondName("Второе")
                                               .Please()),
                    _ => Given_candidate(GiveMe.Candidate()
                                               .WithId(Guid.Empty)
                                               .WithFirstName("Первое Первое")
                                               .WithSecondName("Второе Второе")
                                               .Please()),
                    _ => When_add_candidate(),
                    _ => When_add_candidate(),
                    _ => Then_we_should_have_candidates())
                .RunAsync();
```

Ну и про данные кандидата то-же самое, ты их не тестируешь - нет смысла в их инициализации

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/AddCandidate_feature.cs
> +                                                                  .Please()),
В данном тесте тебе достаточно указать только `GiveMe.Candidate()`. Зачем инициализация всего остального? Ты не проверяешь ведь эти данные. А по-умолчанию у тебя внутри строителя кандидата уже есть дефолтная инициализация

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/CandidateBuilder.cs
> +    public  class CandidateBuilder
странная привычка после public делать еще 1 пробел

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +    public partial  class DeleteCandidate_feature
Опять пробельчик после partial

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/CandidateBuilder.cs
> +        private Guid id;
А шо ты его оставил не инициализированным? Бедный айдишник, дай ему новый гуид хотя-бы `Guid.NewGuid()`

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +        public async Task Candidate_should_be_deleted_in_database()
`Candidate_should_be_deleted_from_database` - лаконичнее

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +            await CandidatesService.AddCandidate(candidateBeforeInsert);
Еееехехехеххехе неееееее, так не пойдет))

Как я тебе говорил, в каждом тесте используется подход GWT. Где W (When) - это то, какой метод должен быть проверен тестом. А тут ты че получается, проверяешь 2 метода? `AddCandidate` и `DeleteCandidate`. Непорядок, непорядок.

Инициализация кандидата в базе данных (которого ты впоследствии в рамках теста будешь удалять) относится к категории "Дано" (Given). Соответственно, ты можешь сделать либо 2 Given (Один создает кандидата, другой записывает его в бд) либо один (который делает все сразу, и создание кандидата и сохранение в бд).
Я бы пошел по более простому пути. Что-то типа:

```cs
public async Task Given_candidate_in_database(CandidateDocument candidateDocument)
{
    await CandidatesRepository.AddCandidate(candidateDocument); // Сохраняем прямо в репу! Не через сервис!
}
```

И всьо, у тебя в базе есть кандидат.

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +        public async Task When_delete_candidates()
Пустые строки между методами! Аксиома!

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +        public async Task Then_database_should_not_contain_candidate()
Пустые строки между методами! Аксиома!

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature_definitions.cs
> +        }
Ну тут страшновато, конечно, удалить всех кандидатов из бд, как-то жестко.
Тебе ж нужно проверить удаление конкретного кандидата. Давай конкретно это и проверим.

Или так:
```cs
When_delete_candidate_with_id(Guid candidateId)
```

Или так, чтобы у тебя при сохранении кандидата в бд - он также сохранялся в приватное поле. А потом айдишник можно из приватного поля достать.

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/GetCandidates_feature.cs
> +        }
По поводу When тоже самое что и в Deleted* тестах. Ты тут тестируешь не добавление кандидата, а **получение**, значит ты должен в блоке When вызывать метод получения кандидатов. Вся инициализация внутри базы должна происходить на стадии Given через репу.

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/GetCandidates_feature_definitions.cs
> +        public async Task When_add_candidate()
Пустая строка между методами!

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/GetCandidates_feature_definitions.cs
> +        }
Снова название определения не доносит суть.

Кто мы?))

```cs
Then_received_candidates_should_exist()
// Или
Then_received_candidates_count_should_be(int candidatesCount) // И проверить на количество кандидатов.
```

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/GetCandidates_feature_definitions.cs
> +            var candidates = await CandidatesService.GetAllCandidates();
Ты вызываешь тестируемый метод в блоке Then. Сильная ошибка. Он должен вызываться в блоке When.
Используй приватные поля для шаринга данных.

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/WhenAddCandidate.cs
> +            var candidateBeforeInsert = new CandidateDocument
`candidateBeforeAddition`

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/WhenAddCandidate.cs
> +        public async Task CandidateDocumentIdShouldBeNewGuid()
Конкретизируй имя теста согласно условию внутри теста.

```cs
CandidateDocumentIdShouldNotBeEmptyGuid()
```

2021-11-19 06:22 UTC, picolino commented on src/Bruhunter.Tests/WhenAddCandidate.cs
> +            Assert.NotEqual(Guid.Empty,candidate.Id);
Пробел между параметрами!

2021-11-22 19:14 UTC, picolino commented on src/Bruhunter.Tests/AddCandidate_feature_definitions.cs
> +            Assert.Single(candidates);
Обосрался, забыл что в `AddCandidate` создается новый `Guid` для кандидата

2021-11-22 19:21 UTC, 5yxar commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +                               .RunAsync();
Дань, а что тут подразумевается под данными кандидата?

2021-11-22 19:27 UTC, picolino commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +                               .RunAsync();
Не помню)) забей

2021-11-22 19:27 UTC, 5yxar commented on src/Bruhunter.Tests/DeleteCandidate_feature.cs
> +                               .RunAsync();
Понял что за данные

2021-11-22 19:37 UTC, 5yxar commented on src/Bruhunter.Tests/CandidateBuilder.cs
> +        private Guid id;
Потому что смысла то особо не имеет 
Он ведь инициализируется в на стороне сервиса
Или нужно все равно?

2021-11-22 19:44 UTC, picolino commented on src/Bruhunter.Tests/CandidateBuilder.cs
> +        private Guid id;
Нужно конечно, ты ведь строишь кандидата не только для добавления, ты можешь напрямую кандидата в базу записать с нужным тебе айдишником через репозиторий а потом удалить его

2021-11-29 20:36 UTC, picolino requested changes

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/DeleteCandidate_feature.cs
> +        }
Не идеальный, конечно, тест на удаление кандидата, но пойдет

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/DeleteCandidate_feature_definitions.cs
> +        private CandidateDocument candidateBeforeAddition;
А это зочем?)

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/GetCandidates_feature.cs
> +                    _ => Then_received_candidates_count_should_be(candidatesCountMustBeAdded))
Тут лучше не использовать приватную переменную. С какой целью ты ее добавил? Она только усложняет все. Просто прокинь сюда двойку и не парься

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/GetCandidates_feature_definitions.cs
> +        public async Task Given_candidate_in_database(CandidateDocument candidateDocument)
Ну сколько можно, пустые линии между компонентами(

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/GetCandidates_feature_definitions.cs
> +        public async Task When_receive_candidates()
Same^

2021-11-29 20:36 UTC, picolino commented on src/Bruhunter.Tests/UnitTests/CandidatesServiceTests/WhenAddCandidate.cs
> +            var service = new CandidatesService(candidatesRepository);
Нет смысла регистрировать тут мок и сервис. У тебя все зарегистрировано уже в базовом классе `TestBase`. Просто используй их как в первом тесте и всё

2021-12-01 06:32 UTC, 5yxar commented on src/Bruhunter.Tests/IntegrationTests/Features/DeleteCandidate_feature.cs
> +        }
Потому что удаляется не один, а все?

2021-12-01 06:38 UTC, 5yxar commented on src/Bruhunter.Tests/UnitTests/CandidatesServiceTests/WhenAddCandidate.cs
> +            var service = new CandidatesService(candidatesRepository);
Тут штука, такая что, у меня в CandidatesRepository из TestBase реализовывает интерфейс ICanditdatesRepostitory в котором моковские методы инкапсулированы и я не могу их использовать. Поэтому в добавлении у меня получилось реализовать использование текстBase а здесь нет

2021-12-01 06:43 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/DeleteCandidate_feature.cs
> +        }
ну типа

2021-12-01 06:45 UTC, picolino commented on src/Bruhunter.Tests/UnitTests/CandidatesServiceTests/WhenAddCandidate.cs
> +            var service = new CandidatesService(candidatesRepository);
Дак ты сделай в `TestBase` не интерфейс, а прям моковский класс. И все у тебя будет доступно. В тестах нет смысла хранить интерфейс, обычно тебе нужна только конкретная имплементация. Можешь даже свойство назвать `CandidatesRepositoryMock`

2021-12-01 06:46 UTC, 5yxar commented on src/Bruhunter.Tests/UnitTests/CandidatesServiceTests/WhenAddCandidate.cs
> +            var service = new CandidatesService(candidatesRepository);
Ну получается что нахрен он не нужен тогда интерфейс

2021-12-01 06:47 UTC, picolino commented on src/Bruhunter.Tests/UnitTests/CandidatesServiceTests/WhenAddCandidate.cs
> +            var service = new CandidatesService(candidatesRepository);
Ну как не нужен, ты подменяешь ведь все равно, ты засовываешь мок в сервис, а не реальный репозиторий

2021-12-01 06:54 UTC, picolino approved these changes

2021-12-01 06:55 UTC, merged