Added logger to CandidateService
5yxar/Bruhunter pull request #14
Opened 2021-12-05 10:56 UTC by 5yxar

### ✨ Изменения какого характера входят в данный PR? (Фикс бага, фича)
Добавлена фича - логгирование CandidatesService.
### ⤵️ Текущее поведение системы
Отсутствует логгирование.
### 🆕 Новое поведение системы
Класс CandidatesService логгируется.
### 🐛 Рекомендации для тестирования
-
### 📝 Ссылки на связанные задачи
https://github.com/5yxar/Bruhunter/issues
### Чеклист (заполняется ревьюером)
- [ ] Соблюдается сервисная архитектура
- [ ] Не добавляются лишние ссылки между проектами
- [ ] Сборка проходит
- [ ] Тесты проходят

2021-12-05 12:35 UTC, picolino requested changes

2021-12-05 12:35 UTC, picolino commented on src/Bruhunter.Api/appsettings.Development.json
> +      "Default": "Debug",
А почему дебаг? В задаче явно же написано уровень по-умолчанию выставить в инфо

2021-12-05 12:35 UTC, picolino commented on src/Bruhunter.Api/appsettings.json
> +      "Default": "Debug",
Same

2021-12-05 12:35 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogDebug("{candidatesCount} candidates was received from database.", receivedCandidates.ToList().Count());
Можно просто `.Count()`

2021-12-05 12:35 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogDebug("Candidate with id = {candidateDocument.Id} was changed in database.", candidateDocument.Id);
В этом методе не логируется сам кандидат. Лучше залогировать, чтобы увидеть что меняется в кандидате

2021-12-06 08:38 UTC, 5yxar commented on src/Bruhunter.Api/appsettings.Development.json
> +      "Default": "Debug",
"Твердость не тупость"

2021-12-06 08:40 UTC, 5yxar commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogDebug("{candidatesCount} candidates was received from database.", receivedCandidates.ToList().Count());
Круто, не знал, это тоже линковая тема получается

2021-12-06 10:02 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +                            candidateDocument.Id, candidateDocument.FirstName,candidateDocument.SecondName);
Да напиши просто `{candidateDocument}`, там же и так все поля будут перечислены =) Перечислять каждый раз - это убийственно, при добавлении нового поля придется переделывать

2021-12-06 10:02 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogInformation("Change the candidate with id = {candidateDocument.Id} in the database ...", candidateDocument.Id);
И тут тоже нехватает `{candidateDocument}`

2021-12-07 17:20 UTC, picolino approved these changes

2021-12-07 17:20 UTC, merged