Feature 17 linking vacancy to candidate
5yxar/Bruhunter pull request #18
Opened 2022-01-29 15:50 UTC by 5yxar

### ✨ Изменения какого характера входят в данный PR? (Фикс бага, фича)
Фича позволившая связать логику вакансий и кандидатов
### ⤵️ Текущее поведение системы
Вакансии и кандидаты ведут себя обособлено
### 🆕 Новое поведение системы
Можно добавить существующую акутальную вакансию для кандидата, изменить ее. 
При изменении Наименовании вакансии в листе вакансий, она будет изменена в карточке кандидата
### 🐛 Рекомендации для тестирования
-
### 📝 Ссылки на связанные задачи
https://github.com/5yxar/Bruhunter/issues/17
### Чеклист (заполняется ревьюером)
- [ ] Соблюдается сервисная архитектура
- [ ] Не добавляются лишние ссылки между проектами
- [ ] Сборка проходит
- [ ] Тесты проходят

2022-01-30 10:32 UTC, picolino requested changes
- [ ] Когда у нас нет ни одной доступной вакансии для выбора при создании кандидата (отсутствуют вакансии дата предполагаемого закрытия которых в будущем) - мы получаем ошибку. В этом случае у нас не должно быть возможности выбрать вакансию и, следовательно, создать кандидата.

- [ ] Можно начинать писать тесты на функционал после внесения правок по ревью.

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            await candidatesService.AddCandidate(candidateDocument);
Эт шо такое за отступ?)

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            this.vacanciesService = vacanciesService;
Зачем тут `vacanciesService `? Ты ж его не используешь

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +        public VacanciesController(VacanciesService vacanciesService,CandidatesService candidatesService)
Пробел между параметрами обязателен

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +            return await vacanciesService.QueryVacancies(minCloseDateTime != null ? Convert.ToDateTime(minCloseDateTime) : null) ;
А если указать тип `DateTime?` не работает?

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +        public async Task UpdateCandidateVacancyTitles (CandidateVacancyDocumentProjection candidateVacancyDocumentProjection)
Между методом и скобками для параметров не должно быть пробела

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            var candidatesCollection = (await GetAllCandidates()).Where(o => o.Vacancy != null && o.Vacancy.Id == candidateVacancyDocumentProjection.Id);
Не ну эт жестко, сделай отдельный метод в репозитории кандидатов на получение кандидатов по айдишнику вакансии. Выглядит ужасно.

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            foreach (var item in candidatesCollection)
Ну не `item` а `candidate`, тут лучше детерминировать

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.DataAccessLayer/ICandidatesRepository.cs
> +        Task UpdateCandidates(IEnumerable<CandidateDocument> tmp);
`tmp`?

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Shared/Documents/CandidateVacancyDocumentProjection.cs
> +namespace Bruhunter.Shared.Documents
Давай лучше засунем это в `Bruhunter.Shared/Projections`
Чтобы подсветить еще раз что это не доменная сущность

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/FeatureFixtureBase.cs
> +            VacanciesService = new VacanciesService(VacanciesRepository,CandidatesService);
Пробел между параметрами!

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Application/VacanciesService.cs
> +        public async Task<IEnumerable<VacancyDocument>> QueryVacancies(DateTime? minCloseDateTime)
Можно написать так:
```cs
public async Task<IEnumerable<VacancyDocument>> QueryVacancies(DateTime? minCloseDateTime = null)
```

Тогда можно будет вызвать просто `QueryVacancies()` и туда автоматически встанет `null` в параметр. Это называется параметр по умолчанию.

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.Tests/UnitTests/Mocks/CandidatesRepositoryMock.cs
> +        public Task UpdateCandidates(IEnumerable<CandidateDocument> tmp)
tmp >_>

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +    async Task SelectVacanciesComboBox_ChangeSelection(ChangeEventArgs e)
Есть ощущение, что селектор можно забиндить сразу на поле `selectedVacancy`. Погугли этот момент и поэксперементируй. Нам ни к чему дополнительный код ручного биндинга.

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.WebApp/Pages/EditCandidateModal.razor
> +    void SelectVacanciesComboBox_ChangeSelection(ChangeEventArgs e)
То же что и выше ^

2022-01-30 10:32 UTC, picolino commented on src/Bruhunter.WebApp/Pages/EditVacancyModal.razor
> +                <input @bind="@vacancyDocument.Title" type="text" class="form-control" id="title"  />
Шо это за пробельчик такой

2022-01-30 20:05 UTC, 5yxar commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            await candidatesService.AddCandidate(candidateDocument);
Это я наоборот поправил коммит который делал до этого, тут все в порядке)

2022-01-30 20:11 UTC, 5yxar commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +            return await vacanciesService.QueryVacancies(minCloseDateTime != null ? Convert.ToDateTime(minCloseDateTime) : null) ;
Да, в этом изначально была проблема, как я понял он передает ее как строку, и когда видит параметр со сложным типом данных, ломался

2022-01-30 20:29 UTC, 5yxar commented on src/Bruhunter.DataAccessLayer/ICandidatesRepository.cs
> +        Task UpdateCandidates(IEnumerable<CandidateDocument> tmp);
...

2022-01-30 20:44 UTC, 5yxar commented on src/Bruhunter.WebApp/Pages/EditVacancyModal.razor
> +                <input @bind="@vacancyDocument.Title" type="text" class="form-control" id="title"  />
жертва ЭЭЭЭЭЭкспериментов

2022-01-31 09:51 UTC, picolino commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +            return await vacanciesService.QueryVacancies(minCloseDateTime != null ? Convert.ToDateTime(minCloseDateTime) : null) ;
Если отформатировать дату в нужном формате перед отправкой, то все заработает:

```cs
var dt = DateTime.Now.ToString("s");
var vacancies = await Http.GetFromJsonAsync<List<VacancyDocument>>($"api/vacancies/query?minCloseDateTime={dt}");
```

```cs
[HttpGet]
[Route("query")]
public async Task<IEnumerable<VacancyDocument>> QueryVacancies([FromQuery] DateTime? minCloseDateTime)
{
    return await vacanciesService.QueryVacancies(minCloseDateTime) ;
}
```

2022-01-31 11:31 UTC, 5yxar commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +            return await vacanciesService.QueryVacancies(minCloseDateTime != null ? Convert.ToDateTime(minCloseDateTime) : null) ;
Ну как есть Царь!

2022-02-01 13:11 UTC, picolino requested changes

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Api/Controllers/VacanciesController.cs
> +        public async Task<IEnumerable<VacancyDocument>> QueryVacancies([FromQuery]DateTime? minCloseDateTime)
После атрибута нужен пробельчик
```cs
...([FromQuery] DateTime? minCloseDateTime)
```

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +        public async Task UpdateCandidateVacancyTitles(CandidateVacancyDocumentProjection candidateVacancyDocumentProjection)
Тут предлагаю чтобы наименование не отражало каждое изменяемое поле. Иначе если нам придется менять миллиард полей - то мы обосремся вписывать в название.

Просто `UpdateCandidateVacancyProjection` будет достаточно думаю

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            changedCandidatesCollection.ForEach(o => o.Vacancy.Title = candidateVacancyDocumentProjection.Title);
Предлагаю последовать практикам функционального программирования, как обсуждали, использовать with record'ов

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogInformation("Changing candidates vacancy titles with vacancy id = {VacancyId} in the database ...",
Тоже убери titles, просто, происходит обновление вакансии в кандидатах

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            logger.LogDebug("Candidates vacancy titles was changed to {candidateVacancyDocumentProjection}.",
Тоже убери titles, просто, происходит обновление вакансии в кандидатах

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.DataAccessLayer/CandidatesRepository.cs
> +            return collection.FindAll().Where(o => o.Vacancy != null && o.Vacancy.Id == id);
Тут лучше использовать метод `Find(...)`, там должен быть предикат, который можно использовать как в Where.
Упрощаем код и оптимизируем. Круто

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Shared/Documents/VacancyDocument.cs
>  {
record!

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Shared/Projections/CandidateVacancyDocumentProjection.cs
> +    public class CandidateVacancyDocumentProjection
record

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Tests/Common/CandidateBuilder.cs
> +                Vacancy = new CandidateVacancyDocumentProjection { Id = vacancyId, Title = vacancyTitle }
красиво, вот в этом классе прям все грамотно сделал

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Tests/Common/VacancyBuilder.cs
> +        public CandidateVacancyDocumentProjection CandidateProjectionPlease()
Годнота

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/Candidate/UpdateCandidateVacancyTitles_feature - Copy.cs
> +    public partial class UpdateCandidateVacancyTitles_feature : FeatureFixtureBase
Поправь название **файла**. Убери Copy

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.Tests/IntegrationTests/Features/Candidate/UpdateCandidateVacancyTitles_feature_definitions - Copy.cs
> +    public partial class UpdateCandidateVacancyTitles_feature
Поправь название **файла**. Убери Copy

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +                    Vacancy = candidateVacanciesProjection.Where(o => o.Id == selectedActualVacancyId).Single()
Красота

2022-02-01 13:11 UTC, picolino commented on src/Bruhunter.WebApp/Pages/EditCandidateModal.razor
> +                                                                .DefaultIfEmpty(candidateDocument.Vacancy)
Ваще красота

2022-02-02 12:12 UTC, picolino approved these changes

2022-02-02 12:13 UTC, merged