Добавлены новые класс, контроллер, ендпоинты методов для Candidate. С…
5yxar/Bruhunter pull request #4
Opened 2021-10-10 18:58 UTC by 5yxar

…оздан место для отображения всех кандидатов во вкладке Candidates

### ✨ Изменения какого характера входят в данный PR? (Фикс бага, фича)
фича
### ⤵️ Текущее поведение системы
Работа по встроенным дефолтным шаблонам проектов
### 🆕 Новое поведение системы
Добавление собственных объектов и методов взаимодействия с объектами Кандидат и добавление "мест" в коде для отображения
### 🐛 Рекомендации для тестирования

### 📝 Ссылки на связанные задачи

### Чеклист (заполняется ревьюером)
- [ ] Соблюдается сервисная архитектура
- [ ] Не добавляются лишние ссылки между проектами
- [ ] Сборка проходит
- [ ] Тесты проходят

2021-10-11 02:23 UTC, picolino requested changes
В целом неплохо, основная задача решена, есть несколько недочётов, которые нужно устранить перед выкаткой в мастер.

На данный момент тебе крайне важно уделять внимание не только "логике", которую ты пишешь, но и форматированию кода, его красоте, стилизации, соблюдению правил его оформления.

Это важно, так как если правила осядут в подкорке - ты автоматически будешь писать хороший код. А код пишется в первую очередь для людей, а уже потом для компужахтера. Так что это правило становится крайне важным.

2021-10-11 02:23 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +@namespace Bruhunter.Shared.Documents
Код лучше структурировать так, чтобы "более общие" элементы стояли выше, а "более конкретные" - ниже.

В данном случае подключение неймспейса более общее, чем инжект HttpClient, эта строка должна быть первой, а инжект - второй

2021-10-11 02:23 UTC, picolino commented on src/Bruhunter.Shared/Documents/CandidateDocument.cs
> +        public long GuidId { get; set; }
Неплохо ты обошел требования задачи))

Есть отдельный тип - `System.Guid`, который дословно расшифровывается как `Globally Unique Identifier`.

Наименование твоего поля получилось в итоге таким:
`Globally Unique Identifier Identifier`, что немного некорректно)

Также твое поле не является "глобальным уникальным идентификатором", так как имеет числовой тип.

Для корректного объявления этого поля, согласно требованиям задачи, нужно сделать так:

```cs
using System;

//...

public Guid Id { get; set; }

//...
```

**И поправить в остальных местах.**

Для создания нового глобального уникального идентификатора используется статический метод `Guid.NewGuid()`. Каждый раз он возвращает новый уникальный идентификатор с минимально возможной вероятностью коллизии.

2021-10-11 02:23 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidateController.cs
> +        public void DeleteCandidate(int GuidId)
Согласно рекомендациям Майкрософт по оформлению стилистики кода, наименование параметров методов должно начинаться с маленькой буквы. Это аксиома, запомни.

За подробностями: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

2021-10-11 02:23 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidateController.cs
> +        public IEnumerable<CandidateDocument> GetCandidate(int Guidid)
Согласно рекомендациям Майкрософт по оформлению стилистики кода, каждое слово, входящее в состав наименования (исключая первое слово, там зависит от контекста) должно начинаться с большой буквы. Это аксиома, запомни.

За подробностями: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

2021-10-11 02:23 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidateController.cs
> +        public IEnumerable<CandidateDocument> allCandidates()
Согласно рекомендациям Майкрософт по оформлению стилистики кода, наименование методов должно всегда начинаться с большой буквы. Это аксиома, запомни.

За подробностями: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

2021-10-11 17:42 UTC, picolino requested changes

2021-10-11 17:42 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidateController.cs
> +
Лишняя пустая строчка. Следи за форматированием.

2021-10-11 17:42 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidateController.cs
> +
Лишняя пустая строчка. Следи за форматированием.

2021-10-11 17:42 UTC, picolino commented on src/Bruhunter.Shared/Documents/CandidateDocument.cs
> +
Лишняя пустая строчка. Следи за форматированием.

2021-10-11 17:42 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +
Лишняя пустая строчка. Следи за форматированием.

2021-10-21 17:45 UTC, 5yxar commented
Поправил все, согласно замечаниям. 
Тут нужно еще раз делать как то запрос на слияние?

2021-10-21 19:27 UTC, picolino requested changes

2021-10-21 19:27 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +@namespace Bruhunter.Shared.Documents
Ты не исправил согласно комментариям. Более общие элементы - выше.

2021-10-21 19:30 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +                <th>GuidId</th>
`GuidId` -> `Id`

2021-10-21 19:44 UTC, picolino approved these changes
Approved

2021-10-21 19:45 UTC, merged