Feature 5 create delete show candidates
5yxar/Bruhunter pull request #6
Opened 2021-10-30 13:49 UTC by 5yxar

### ✨ Изменения какого характера входят в данный PR? (Фикс бага, фича)
Реализация статического листа объектов, который выступает в роли хранилища (БД) 
Создание, получение, удаление данных в  WebApp через WebAPI
### ⤵️ Текущее поведение системы
Всего что описано выше нет 
### 🆕 Новое поведение системы
- Добавлены поля для ввода данных имени и фамилии пользователя
- Обработка ситуации когда пользователь хочет внести пустое имя или фамилии 
- Идентификатор нового кандидата создается на стороне сервера
- Есть возможность удалить конкретного кандидата из базы
### 🐛 Рекомендации для тестирования
-
### 📝 Ссылки на связанные задачи
https://github.com/5yxar/Bruhunter/issues/5
### Чеклист (заполняется ревьюером)
- [ ] Соблюдается сервисная архитектура
- [ ] Не добавляются лишние ссылки между проектами
- [ ] Сборка проходит
- [ ] Тесты проходят

2021-10-30 18:14 UTC, picolino requested changes
Не ожидал что столько кода продублируешь в `.razor`. Печальненько :C

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            return this.candidatesService.GetAllCandidates();
Тут ключевое слово `this` не нужно. Если в конструкторе это оправдано (там и в методе параметр `candidatesService` и поле в классе тоже `candidatesService`, мы говорим компилятору, что нужно параметр положить в поле класса с помощью `this`), то тут - нет. Можно обойтись без него, компилятор все поймет.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            this.candidatesService.AddCandidate(candidateDocument);
Тут ключевое слово `this` не нужно. Если в конструкторе это оправдано (там и в методе параметр `candidatesService` и поле в классе тоже `candidatesService`, мы говорим компилятору, что нужно параметр положить в поле класса с помощью `this`), то тут - нет. Можно обойтись без него, компилятор все поймет.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Api/Controllers/CandidatesController.cs
> +            this.candidatesService.DeleteCandidate(id);
Тут ключевое слово `this` не нужно. Если в конструкторе это оправдано (там и в методе параметр `candidatesService` и поле в классе тоже `candidatesService`, мы говорим компилятору, что нужно параметр положить в поле класса с помощью `this`), то тут - нет. Можно обойтись без него, компилятор все поймет.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Api/Startup.cs
> +            services.AddSingleton<CandidatesService>();
Давай выделим регистрацию зависимостей в отдельный метод, чтобы отделить от остальных настроек. Сервисов-зависимостей у нас в будущем будет не мало.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +        public List<CandidateDocument> GetAllCandidates()
Согласно рекомендациям майкрософт необходимо отделять один метод от другого пустой строкой.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +        public void DeleteCandidate(Guid guid)
Согласно рекомендациям майкрософт необходимо отделять один метод от другого пустой строкой.

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.Application/CandidatesService.cs
> +            }
Данный код можно существенно упростить, просто поискав подходящий метод:

```cs
Candidates.RemoveAll(o => o.Id == guid);
```

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +@using System.Net.Http.Json
Лишний `using`, код из импортируемой либы не используется

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +            candidateDocument.SecondName = lastName;
Этот блок код можно упростить:

```cs
var candidateDocument = new CandidateDocument
{
    FirstName = name,
    SecondName = lastName
};
```

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +            JsonContent jsonContent = JsonContent.Create(candidateDocument);
Привыкай использовать ключевое слово `var`, также строку ниже можно инициализировать прямиком в методе `Create`:

```cs
var jsonContent = JsonContent.Create(candidateDocument, new MediaTypeHeaderValue("application/json"));
```

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +        candidates = await Http.GetFromJsonAsync<List<CandidateDocument>>("api/candidates/query");
Дублирование кода

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +        candidates = await Http.GetFromJsonAsync<List<CandidateDocument>>("api/candidates/query");
Дублирование кода

2021-10-30 18:14 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +            candidates = await Http.GetFromJsonAsync<List<CandidateDocument>>("api/candidates/query");
Дублирование кода

2021-10-30 18:21 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +                    <button @onclick="@(e => DeleteCandidate(candidate.Id))">Click</button>
И почему `Click`? Уж лучше `Удалить` или чет такое

2021-10-30 18:33 UTC, picolino commented
Также есть баг:

1. Вводим имя и фамилию кандидата
1. Создаем кандидата
1. Удаляем имя или фамилию (или оба поля)
1. Создаем кандидата

Результат: Кандидат успешно создается

Ожидаемый результат: Кандидата невозможно создать без имени и фамилии

2021-10-31 11:54 UTC, 5yxar commented
Исправил все согласно рекомендациям, устранил баг

2021-10-31 12:04 UTC, picolino requested changes

2021-10-31 12:04 UTC, picolino commented on src/Bruhunter.Api/Startup.cs
> +        private void AddServiceDependencies(IServiceCollection services)
Между методами нужны отступы. Всегда

2021-10-31 12:04 UTC, picolino commented on src/Bruhunter.Api/Startup.cs
> +
А вот после метода, если он последний - отступ не нужен

2021-10-31 12:04 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +    private async Task GetCandidates()
Не очень нравится название метода. `GetCandidates` говорит нам о том, что мы что-то получаем. Но по-факту из метода нам ничего не возвращается, просто происходит изменение внутреннего состояния поля `candidates`. Лучше назвать его `LoadCandidates`, кажется что так будет правильнее

2021-10-31 12:06 UTC, 5yxar commented on src/Bruhunter.Api/Startup.cs
> +        private void AddServiceDependencies(IServiceCollection services)
![image](https://user-images.githubusercontent.com/36841344/139582294-37d89d2d-b6b4-48f8-8119-ec0e1a7d2fcb.png)
немного сбивает эта надпись references, поэтому визуально не всегда понятно

2021-10-31 12:09 UTC, 5yxar commented
Поправил название и отступы

2021-10-31 12:10 UTC, picolino commented on src/Bruhunter.WebApp/Pages/Candidates.razor
> +    private int id;
Поле `id` не используется

2021-10-31 12:14 UTC, 5yxar commented
Удалил неиспользуемые компоненты

2021-10-31 12:17 UTC, picolino approved these changes

2021-10-31 12:17 UTC, merged